# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search_Engine_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1387, 791)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(249, 255, 220);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(30)
        self.header.setFont(font)
        self.header.setStyleSheet("padding: 20px;\n"
"background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.header.setTextFormat(QtCore.Qt.RichText)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.seachBoxW = QtWidgets.QWidget(self.centralwidget)
        self.seachBoxW.setObjectName("seachBoxW")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.seachBoxW)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchBoxWI = QtWidgets.QWidget(self.seachBoxW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBoxWI.sizePolicy().hasHeightForWidth())
        self.searchBoxWI.setSizePolicy(sizePolicy)
        self.searchBoxWI.setMaximumSize(QtCore.QSize(16777215, 100))
        self.searchBoxWI.setStyleSheet("border-color: rgb(214, 214, 214);\n"
"background-color: rgb(209, 209, 209);\n"
"border-width: 5px;\n"
"border-radius: 25px;")
        self.searchBoxWI.setObjectName("searchBoxWI")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.searchBoxWI)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.searchBox = QtWidgets.QLineEdit(self.searchBoxWI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBox.sizePolicy().hasHeightForWidth())
        self.searchBox.setSizePolicy(sizePolicy)
        self.searchBox.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.searchBox.setFont(font)
        self.searchBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.searchBox.setAlignment(QtCore.Qt.AlignCenter)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_2.addWidget(self.searchBox)
        self.verticalLayout_2.addWidget(self.searchBoxWI)
        self.searchResult = QtWidgets.QLabel(self.seachBoxW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchResult.sizePolicy().hasHeightForWidth())
        self.searchResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.searchResult.setFont(font)
        self.searchResult.setText("")
        self.searchResult.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.searchResult.setObjectName("searchResult")
        self.verticalLayout_2.addWidget(self.searchResult)
        self.verticalLayout.addWidget(self.seachBoxW)
        self.buttonW = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonW.sizePolicy().hasHeightForWidth())
        self.buttonW.setSizePolicy(sizePolicy)
        self.buttonW.setObjectName("buttonW")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonW)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBtn = QtWidgets.QPushButton(self.buttonW)
        self.searchBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchBtn.sizePolicy().hasHeightForWidth())
        self.searchBtn.setSizePolicy(sizePolicy)
        self.searchBtn.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("georgia")
        font.setPointSize(28)
        self.searchBtn.setFont(font)
        self.searchBtn.setStyleSheet("font-family: georgia;\n"
"font-size: 28pt;\n"
"font-style: italic;\n"
"border-style: solid;\n"
"font-weight: bold;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"border-radius: 10px;\n"
"background-color: rgb(229, 229, 229);\n"
"color: rgb(0, 85, 0);")
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.verticalLayout.addWidget(self.buttonW)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "CPP Civil Engineering Research Search Engine"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
